project_id = "xznmawsbuifpgppybevs"

[functions.parse-contract-pdf]
verify_jwt = false

[functions.sign-contract]
verify_jwt = false

[functions.parse-statement-pdf]
verify_jwt = false

[functions.google-oauth-callback]
verify_jwt = false

[functions.google-calendar-sync]
verify_jwt = false

